name: openclima
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  provider: ^6.0.5
  another_flushbar: ^1.12.30
  animate_do: ^3.1.2
  google_place: ^0.4.7
  dio: ^5.3.3
  countup: ^0.1.4
  flutter_keyboard_visibility: ^6.0.0
  focus_detector: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/iconApp.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/foreground.png"  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/
    - assets/animations/
    - assets/sounds/
    - assets/translations/
    - assets/fonts/
    - assets/icons/
    - assets/icons/Astronomical/
    - assets/icons/Astronomical/Day/
    - assets/icons/Astronomical/Day/Sunrise/
    - assets/icons/Astronomical/Day/Sunset/
    - assets/icons/Astronomical/Night/
    - assets/icons/Astronomical/Night/Moonrise/
    - assets/icons/Astronomical/Night/Moonset/
    - assets/icons/Day/
    - assets/icons/Day/Rain/
    - assets/icons/Day/Rain/Heavy Freezing Rain/
    - assets/icons/Day/Rain/Heavy Rain/
    - assets/icons/Day/Rain/Light Freezing Rain/
    - assets/icons/Day/Rain/Light Rain/
    - assets/icons/Day/Rain/Moderate Rain/
    - assets/icons/Drizzle/
    - assets/icons/Drizzle/Day/
    - assets/icons/Drizzle/Day/Dense Drizzle/
    - assets/icons/Drizzle/Day/Dense Freezing Drizzle/
    - assets/icons/Drizzle/Day/Light Drizzle/
    - assets/icons/Drizzle/Day/Light Freezing Drizzle/
    - assets/icons/Drizzle/Day/Moderate Drizzle/
    - assets/icons/Drizzle/Night/
    - assets/icons/Drizzle/Night/Dense Drizzle/
    - assets/icons/Drizzle/Night/Dense Freezing Drizzle/
    - assets/icons/Drizzle/Night/Light Drizzle/
    - assets/icons/Drizzle/Night/Light Freezing Drizzle/
    - assets/icons/Drizzle/Night/Moderate Drizzle/
    - assets/icons/Dust/
    - assets/icons/Dust/Day/
    - assets/icons/Dust/Day/Dust/
    - assets/icons/Dust/Night/
    - assets/icons/Dust/Night/Dust/
    - assets/icons/Fog/
    - assets/icons/Fog/Day/
    - assets/icons/Fog/Day/Fog/
    - assets/icons/Fog/Day/Rime Fog/
    - assets/icons/Fog/Night/
    - assets/icons/Fog/Night/Fog/
    - assets/icons/Hail/
    - assets/icons/Hail/Day/
    - assets/icons/Hail/Day/Hail/
    - assets/icons/Hail/Night/
    - assets/icons/Hail/Night/Hail/
    - assets/icons/Haze/
    - assets/icons/Haze/Day/
    - assets/icons/Haze/Day/Haze/
    - assets/icons/Haze/Night/
    - assets/icons/Haze/Night/Haze/
    - assets/icons/Meteorological/
    - assets/icons/Meteorological/Day/
    - assets/icons/Meteorological/Day/Rainbow/
    - assets/icons/Meteorological/Day/Rainbow Alt 1/
    - assets/icons/Meteorological/Day/Rainbow Alt 2/
    - assets/icons/Meteorological/Night/
    - assets/icons/Meteorological/Night/Moonbow/
    - assets/icons/Meteorological/Night/Moonbow Alt 1/
    - assets/icons/Meteorological/Night/Moonbow Alt 2/
    - assets/icons/Miscellaneous/
    - assets/icons/Miscellaneous/Day/
    - assets/icons/Miscellaneous/Day/Air Filter/
    - assets/icons/Miscellaneous/Day/Celsius/
    - assets/icons/Miscellaneous/Day/Dew Point/
    - assets/icons/Miscellaneous/Day/Fahrenheit/
    - assets/icons/Miscellaneous/Day/Humidity/
    - assets/icons/Miscellaneous/Day/Map Pin/
    - assets/icons/Miscellaneous/Day/Null/
    - assets/icons/Miscellaneous/Day/Rainfall Measure/
    - assets/icons/Miscellaneous/Day/Rainfall Measure Alt/
    - assets/icons/Miscellaneous/Day/Thermometer/
    - assets/icons/Miscellaneous/Day/Unknown/
    - assets/icons/Miscellaneous/Day/Windsock/
    - assets/icons/Miscellaneous/Day/Windsock Weak/
    - assets/icons/Miscellaneous/Night/
    - assets/icons/Miscellaneous/Night/Air Filter/
    - assets/icons/Miscellaneous/Night/Celsius/
    - assets/icons/Miscellaneous/Night/Dew Point/
    - assets/icons/Miscellaneous/Night/Fahrenheit/
    - assets/icons/Miscellaneous/Night/Humidity/
    - assets/icons/Miscellaneous/Night/Map Pin/
    - assets/icons/Miscellaneous/Night/Null/
    - assets/icons/Miscellaneous/Night/Rainfall Measure/
    - assets/icons/Miscellaneous/Night/Rainfall Measure Alt/
    - assets/icons/Miscellaneous/Night/Thermometer/
    - assets/icons/Miscellaneous/Night/Unknown/
    - assets/icons/Miscellaneous/Night/Windsock/
    - assets/icons/Miscellaneous/Night/Windsock Weak/
    - assets/icons/Natural Disasters/
    - assets/icons/Natural Disasters/Day/
    - assets/icons/Natural Disasters/Day/Hurricane/
    - assets/icons/Natural Disasters/Day/Tornado/
    - assets/icons/Natural Disasters/Night/
    - assets/icons/Natural Disasters/Night/Hurricane/
    - assets/icons/Natural Disasters/Night/Tornado/
    - assets/icons/Night/
    - assets/icons/Night/Rain/
    - assets/icons/Night/Rain/Heavy Freezing Rain/
    - assets/icons/Night/Rain/Heavy Rain/
    - assets/icons/Night/Rain/Light Freezing Rain/
    - assets/icons/Night/Rain/Light Rain/
    - assets/icons/Night/Rain/Moderate Rain/
    - assets/icons/Night/Snow/
    - assets/icons/Night/Snow/Snowfall/
    - assets/icons/Night/Snow/Snowfall/Heavy Snowfall/
    - assets/icons/Normal Conditions/
    - assets/icons/Normal Conditions/Day/
    - assets/icons/Normal Conditions/Day/Clear/
    - assets/icons/Normal Conditions/Day/Cloudy/
    - assets/icons/Normal Conditions/Day/Mostly Clear/
    - assets/icons/Normal Conditions/Day/Overcast/
    - assets/icons/Normal Conditions/Day/Partly Cloudy/
    - assets/icons/Normal Conditions/Night/
    - assets/icons/Normal Conditions/Night/Clear/
    - assets/icons/Normal Conditions/Night/Cloudy/
    - assets/icons/Normal Conditions/Night/Mostly Clear/
    - assets/icons/Normal Conditions/Night/Overcast/
    - assets/icons/Normal Conditions/Night/Partly Cloudy/
    - assets/icons/Snow/
    - assets/icons/Snow/Day/
    - assets/icons/Snow/Day/Sleet/
    - assets/icons/Snow/Day/Snowfall/
    - assets/icons/Snow/Day/Snowfall/Heavy Snowfall/
    - assets/icons/Snow/Day/Snowfall/Moderate Snowfall/
    - assets/icons/Snow/Day/Snowfall/Slight Snowfall/
    - assets/icons/Snow/Day/Snowflake/
    - assets/icons/Snow/Night/
    - assets/icons/Snow/Night/Sleet/
    - assets/icons/Snow/Night/Snowfall/
    - assets/icons/Snow/Night/Snowfall/Moderate Snowfall/
    - assets/icons/Snow/Night/Snowfall/Slight Snowfall/
    - assets/icons/Snow/Night/Snowflake/
    - assets/icons/Thunderstorm/
    - assets/icons/Thunderstorm/Day/
    - assets/icons/Thunderstorm/Day/Thunderstorm/
    - assets/icons/Thunderstorm/Day/Thunderstorm with Hail/
    - assets/icons/Thunderstorm/Night/
    - assets/icons/Thunderstorm/Night/Thunderstorm/
    - assets/icons/Thunderstorm/Night/Thunderstorm with Hail/
    - assets/icons/Miscellaneous/Both/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
          style: normal
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 800
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
